version: "3.7"

services:

  test:
    build:
      dockerfile: ./Dockerfile-test
      context: ./
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
      PATHOGEN: "${PATHOGEN_A}"

  postgres:
    image: postgres:15.4-alpine3.18
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    expose:
      - 5432
